//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelevisionModel.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TelevisionModel.Data.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://jaruba.github.io/channel-logos/export/transparent-color/.
        /// </summary>
        internal static string BaseUrl {
            get {
                return ResourceManager.GetString("BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change resolution in this state..
        /// </summary>
        internal static string CannotChangeResolution {
            get {
                return ResourceManager.GetString("CannotChangeResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change volume in this state..
        /// </summary>
        internal static string CannotChangeVolume {
            get {
                return ResourceManager.GetString("CannotChangeVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot switch to next item in content provider in this state..
        /// </summary>
        internal static string CannotSwitchToNext {
            get {
                return ResourceManager.GetString("CannotSwitchToNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot switch to previous item in content provider in this state..
        /// </summary>
        internal static string CannotSwitchToPrevious {
            get {
                return ResourceManager.GetString("CannotSwitchToPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot switch to this state..
        /// </summary>
        internal static string CannotSwitchToThisState {
            get {
                return ResourceManager.GetString("CannotSwitchToThisState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update software in this state..
        /// </summary>
        internal static string CannotUpdateSoftware {
            get {
                return ResourceManager.GetString("CannotUpdateSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state was changed to external device screencast state..
        /// </summary>
        internal static string ChangedToExternalDeviceScreencastState {
            get {
                return ResourceManager.GetString("ChangedToExternalDeviceScreencastState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state was changed to main menu..
        /// </summary>
        internal static string ChangedToMainMenuState {
            get {
                return ResourceManager.GetString("ChangedToMainMenuState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state was changed to streaming state..
        /// </summary>
        internal static string ChangedToStreamingState {
            get {
                return ResourceManager.GetString("ChangedToStreamingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state was changed to television broadcasting state..
        /// </summary>
        internal static string ChangedToTelevisionBroadcastingState {
            get {
                return ResourceManager.GetString("ChangedToTelevisionBroadcastingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state was changed to turned off state..
        /// </summary>
        internal static string ChangedToTurnedOffState {
            get {
                return ResourceManager.GetString("ChangedToTurnedOffState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data/logo_paths.json.
        /// </summary>
        internal static string ChannelsDataRelativePath {
            get {
                return ResourceManager.GetString("ChannelsDataRelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The television channel with the same name already exists..
        /// </summary>
        internal static string ChannelWithTheSameNameAlreadyExistsErrorMessage {
            get {
                return ResourceManager.GetString("ChannelWithTheSameNameAlreadyExistsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to unregister remote control..
        /// </summary>
        internal static string FaildToUnregisterRemoteControlErrorMessage {
            get {
                return ResourceManager.GetString("FaildToUnregisterRemoteControlErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution must be between 0 and MaxResolution.
        /// </summary>
        internal static string ResolutionRestrictionsErrorMessage {
            get {
                return ResourceManager.GetString("ResolutionRestrictionsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The television channel with this name does not exist..
        /// </summary>
        internal static string TelevisionChannelDoesNotExistErrorMessage {
            get {
                return ResourceManager.GetString("TelevisionChannelDoesNotExistErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Data/tv_shows.json.
        /// </summary>
        internal static string TelevisionSeriesPath {
            get {
                return ResourceManager.GetString("TelevisionSeriesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Television to Pair is null..
        /// </summary>
        internal static string TelevisionToPairIsNullErrorMessage {
            get {
                return ResourceManager.GetString("TelevisionToPairIsNullErrorMessage", resourceCulture);
            }
        }
    }
}
